### ISSUE TITLE
Serveral question about dataset

### ISSUE THREAD

**Issue by wheatdog** [JStehouwer/FFD_CVPR2020#6]
Thanks for releasing the code and the dataset. I have some questions for the dataset,

- In `align_faces/align_faces.m` inside `scripts.zip`, there is a file called `box.txt`. But I can't find it anywhere. It seems crucial to align and crop the images.

![image](https://user-images.githubusercontent.com/7741908/87128603-7de7ab00-c2c2-11ea-824c-61e7e6faf154.png)
- All of the images in dataset are in the resolution of 299x299. I wonder how did you process the images in CelebA. I remember the aligned and cropped image in CelebA are in the resolution of 128x128.

**Comment by wheatdog** [comment]
My main question here is, can you share the CelebA part of your dataset (with the resolution of 299x299)?

**Comment by JStehouwer** [comment]
Hi wheatdog.

Thanks for your interest in our work!

The bounding box files are available in the "bounding_boxes.zip" or "all_bounding_box_files.zip" files from the CVLab dataset download page near the bottom of [http://cvlab.cse.msu.edu/dffd-dataset.html](http://cvlab.cse.msu.edu/dffd-dataset.html).

We cannot provide the CelebA data ourselves due to the license agreement for using CelebA. I'm getting in touch with the guy that prepared the CelebA data and will post back here when I have the answer.
