### ISSUE TITLE
Is it possible to release the script for generating edited images by FaceApp?

### ISSUE THREAD

**Issue by zjxgithub** [JStehouwer/FFD_CVPR2020#8]
Hi, 
Thanks for releasing the code and dataset!
Part of your dataset is generated by FaceApp (using automated scripts running on android devices). I am wondering if you could also release this android script? I also plan to generate some edited images using FaceApp, and an automated script will be quite helpful!! 
Thanks!

**Comment by JStehouwer** [comment]
Hi zjxgithub!

Thanks for the interest in our work! I hope that it can help inspire your own.

The requested scripts are now available in the source code. These are designed specifically for the smartphone devices that we used, so you will need to enable developer settings on the device you intend to use to determine the appropriate coordinates for the actions.

Additionally, the app may have changed significantly since we used it, so you may need to develop your own script, but these may serve as examples for how to do so.

**Comment by zjxgithub** [comment]
Cool! Thanks! It really helps!
